- name: install apache and php for Ubuntu Server
  tags: apache,apache2,ubuntu 
  package: 
    name: 
      - "{{ apache_package }}"
      - "{{ php_package }}"
    state: latest

- name: start and enable apache
  tags: apache,httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644