- name: install apache and php for Ubuntu Server
  tags: apache,apache2,ubuntu 
  apt: 
    name: 
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"